### ISSUE TITLE
 Get nested properties

### ISSUE THREAD

**Issue by optical-genius** [waningflow/vue-virtual-table#11]
Thanks so much for wonderful component.

How can I access the nested properties of an object?
`{ prop: 'nested properties here', name: 'HOST', searchable: true },`

![json_prop](https://user-images.githubusercontent.com/25301192/69453730-9af05d80-0d75-11ea-8967-4385b1f3e46a.jpg)

Is it possible to reflect several properties from an array in one column?

Thanks in advance!

**Comment by waningflow** [comment]
Nested properties is not supported now. For a sollution, you can assign the value directly to row data.

**Comment by waningflow** [comment]
Nested properties is not supported now. For a sollution, you can assign the value directly to row data.
