### ISSUE TITLE
add support for justify-content

### ISSUE THREAD

**Issue by Chaho12** [waningflow/vue-virtual-table#29]
Hi, I noticed that [align items](https://developer.mozilla.org/en-US/docs/Web/CSS/align-items) is meant for vertical align and it would be great if we can set horizontal align css style using [justify content](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content) option.

I tested and if you don't mind, I'll make a PR for this change
Document would be as below and UI would be 

param | type | description | required | default
-- | -- | -- | -- | --
alignItems | String | Same with flex. Control the content of a   cell | No | center
justifyContent | String | Defines   how the browser distributes space between and around content items. | No | center

> before
![image](https://user-images.githubusercontent.com/25147023/147540031-b623ef11-0802-410f-a0b4-3d19d45a2259.png)

> after (set age : justify-content left)

![image](https://user-images.githubusercontent.com/25147023/147540069-f34aa00a-4c78-43d5-881a-7a3a4084e10f.png)

**Comment by Chaho12** [comment]
![image](https://user-images.githubusercontent.com/25147023/147540158-17eb49e3-a161-4bdd-88f9-86fdf7094f3d.png)

**Comment by Chaho12** [comment]
also if you don't mind, I would like to add 'ko' version option names

**Comment by waningflow** [comment]
It's OK. BTW, it's more probably spelled as 'kr' instead of 'ko'.
