### ISSUE TITLE
Popover Window does not shows up

### ISSUE THREAD

**Issue by PatDav** [waningflow/vue-virtual-table#3]
Hi There

First I'd like to say thank you for your very impressive component vue-virtual-table.

I'm about to build a big project under VueCLI and your component is just perfect.

Nonetheless I got one major issue. 
When I set in the configuration table "filterable" or "searchable" then the popover window do not shows up.. In real it shows up but very fast and close right after...

Then I can't use that properties which is really helpful.

Could you please help me out ?

Thank you

**Comment by waningflow** [comment]
Hello, the issue should has been fixed in v0.2.9. You can have a check.

**Comment by PatDav** [comment]
Hi

I can confirm that the new release 0.2.9 has fixed the issue.

Nonetheless, could you tell me how to set the property "language" to 'en' or another language if possible, because when that property is used then an error appears in the console.
Herewith couple of screenshot that show how I try to use that "langauge" property and all the lable are in 'cn' chinees. 
Could you please tell how to set this in english or idelly set any type of language....
Thank you 
<img width="1410" alt="Capture d’écran 2019-04-25 à 20 16 38" src="https://user-images.githubusercontent.com/12293203/56760000-8249a600-679a-11e9-927a-7659fec26094.png">
![Capture d’écran 2019-04-25 à 20 18 48](https://user-images.githubusercontent.com/12293203/56760065-ad33fa00-679a-11e9-944a-2890f3344063.png)
<img width="900" alt="Capture d’écran 2019-04-25 à 20 17 22" src="https://user-images.githubusercontent.com/12293203/56760099-bf159d00-679a-11e9-8284-9edf4b1ac649.png">
<img width="756" alt="Capture d’écran 2019-04-25 à 20 17 33" src="https://user-images.githubusercontent.com/12293203/56760105-c3da5100-679a-11e9-918c-9f079d98aefa.png">
<img width="476" alt="Capture d’écran 2019-04-25 à 20 18 36" src="https://user-images.githubusercontent.com/12293203/56760115-cb99f580-679a-11e9-92fc-772bae38dad0.png">

**Comment by PatDav** [comment]
Hi 

we just figured out how to set that property.
As you can see in the screenshot, we have to put a quote.
At first, we set it like this:
:language="en"

Then just by chance we try that:
:language="'en'"

As you can see surrounding the value with the quote then the labels are in English.

I can close that ticket. But I would love to know if other languages could be used.

Thank you for you very nice component

Cheers


![Capture d’écran 2019-04-25 à 20 51 39](https://user-images.githubusercontent.com/12293203/56760736-1bc58780-679c-11e9-954d-bc04670a76cd.png)

<img width="420" alt="Capture d’écran 2019-04-25 à 20 56 22" src="https://user-images.githubusercontent.com/12293203/56760993-a5755500-679c-11e9-841c-0bc3ee1edc14.png">
