### ISSUE TITLE
How I can add class to row?

### ISSUE THREAD

**Issue by EugenMaevskiy** [waningflow/vue-virtual-table#4]
I need conditionally give color to some rows.  
Could you please advise how to do this?

**Comment by waningflow** [comment]
Unfortunately adding class to row is not supported now. But you can add class to a single cell conditionally. 
For example, in `example/complexTable.vue`
```js
{
  prop: "budget",
  name: "Budget",
  sortable: true,
  summary: "SUM",
  prefix: "$",
  eClass: { warningColor: "${daily_budget}<${spend}" },
  numberFilter: true
}
```
Thus you can add `eClass` to all items of config.
The `warningColor` will be the className that you can define in you component.
```css
.warningColor{
    background-color: lightblue;
}
```
